#!/bin/bash
#
# **** License ****
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# A copy of the GNU General Public License is available as
# `/usr/share/common-licenses/GPL' in the Debian GNU/Linux distribution
# or on the World Wide Web at `http://www.gnu.org/copyleft/gpl.html'.
# You can also obtain it by writing to the Free Software Foundation,
# Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.
# 
# This code was originally developed by Vyatta, Inc.
# Portions created by Vyatta are Copyright (C) 2009 Vyatta, Inc.
# All Rights Reserved.
# 
# Author: Stephen Hemminger
# Date: August 2009
# 
# **** End License ****

# Based on Debian /etc/init.d/hostapd

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/hostapd

if [ $# -ne 2 ]; then
    echo "Usage: $0 {start|stop|restart} wlanX" >&2
    exit 1
fi

PIDFILE=/var/run/vyatta/hostapd/$2.pid
DAEMON_CONF=/opt/vyatta/etc/hostapd/$2
DAEMON_OPTS="-B -P $PIDFILE $DAEMON_CONF"
DESC="Access point mangement for $2"

case "$1" in
  start)
	/opt/vyatta/sbin/vyatta-wireless.pl --dev=$2 --hostap > $DAEMON_CONF \
	    && start-stop-daemon --start --oknodo --quiet \
		--exec $DAEMON --pidfile $PIDFILE -- $DAEMON_OPTS > /dev/null
	;;
  stop)
	start-stop-daemon --stop --oknodo --quiet --pidfile $PIDFILE
	;;
  reload)
	/opt/vyatta/sbin/vyatta-wireless.pl --dev=$2 --hostap > $DAEMON_CONF \
	    && start-stop-daemon --stop --signal HUP --pidfile $PIDFILE
	;;
  restart|force-reload)
  	$0 stop
	sleep 8
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload} wlanX" >&2
	exit 1
	;;
esac






