#!/bin/bash
#
# **** License ****
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# A copy of the GNU General Public License is available as
# `/usr/share/common-licenses/GPL' in the Debian GNU/Linux distribution
# or on the World Wide Web at `http://www.gnu.org/copyleft/gpl.html'.
# You can also obtain it by writing to the Free Software Foundation,
# Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
# MA 02110-1301, USA.
# 
# This code was originally developed by Vyatta, Inc.
# Portions created by Vyatta are Copyright (C) 2009 Vyatta, Inc.
# All Rights Reserved.
# 
# Author: Stephen Hemminger
# Date: August 2009
# 
# **** End License ****

PATH=/sbin:/bin:/usr/sbin:/usr/bin

if [ $# -ne 2 ]; then
    echo "Usage: $0 {start|stop|restart} wlanX" >&2
    exit 1
fi

pid_dir=/var/run/vyatta/wpa_supplicant
log_dir=/var/log/vyatta/wpa_supplicant

pid_file=$pid_dir/$2.pid
config=$pid_dir/$2.cfg
log_file=$log_dir/$2

DAEMON=/usr/sbin/wpa_supplicant
DAEMON_OPTS="-B -D nl80211 -i $2 -c $config -f $log_file"

set -e

case "$1" in
  start)
	/opt/vyatta/sbin/wireless-wpa_supplicant.pl $2 > $config
	start-stop-daemon --start --oknodo --quiet \
		--exec $DAEMON --pidfile $pid_file -- $DAEMON_OPTS > /dev/null
	;;
  stop)
	start-stop-daemon --stop --oknodo --quiet --pidfile $pid_file
	;;
  reload)
	/opt/vyatta/sbin/wireless-wpa_supplicant.pl $2 > $config
	start-stop-daemon --stop --signal HUP --pidfile $pid_file
	;;
  restart|force-reload)
  	$0 stop
	sleep 8
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload} wlanX" >&2
	exit 1
	;;
esac



    system("wpa_supplicant -i $wlan -c $cfgname -f $logname -B") == 0
	    or die "can't start wpa_supplicant: $!";
}


